AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - db/schema.rb

Documentation:
  Enabled: false

LineLength:
  Max: 115

Style/SpecialGlobalVars:
  Enabled: false

Metrics/AbcSize:
  Max: 30
